title: BUYACOFFEE.XYZ
description: Buy a Coffee
google_analytics: 
plausible_analytics: buyacoffee.xyz
include:
 - _posts
 - _pages
collections:
  pages:
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /:slug
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"      
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
